"""
Django settings for django_rest_template project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = (
	'grappelli',  # disabled for now
	'django.apps',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'rest_framework',
	# 'elasticapm.contrib.django',

	'django_rest_template.apps.venue',
	'django_rest_template.apps.user',
	'django_rest_template.apps.account',
	'django_rest_template.apps.common',
	'django_rest_template.apps.email',
	'django_rest_template.apps.oauth',
	'django_rest_template.apps.permission',
	'django_rest_template.apps.terminology',

	'django_elasticsearch_dsl',
	'django_elasticsearch_dsl_drf',
	'django_countries',
	'import_export',
	'corsheaders',
	'rest_framework_swagger',
	'weasyprint',
	'xhtml2pdf',
	'reportlab',
	'crispy_forms'
)

SITE_ID = 1

AUTH_USER_MODEL = 'venue.User'

PASSWORD_HASHERS = [
	'django.contrib.auth.hashers.UnsaltedMD5PasswordHasher',
]

# The default customer support email address
DEFAULT_SUPPORT_EMAIL = 'support@djangoresttemplate.com'

ADMIN_EMAIL = 'admin@djangoresttemplate.com'

MIDDLEWARE = (
	'elasticapm.contrib.django.middleware.TracingMiddleware',
	'elasticapm.contrib.django.middleware.Catch404Middleware',
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'corsheaders.middleware.CorsMiddleware',
	'django.middleware.locale.LocaleMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django_rest_template.apps.venue.middleware.VenueMiddleware',
	'django_rest_template.apps.venue.middleware.RestrictStaffToAdminMiddleware'
)

DEFAULT_OPTS = {
	'HOST': os.getenv('DB_HOST', 'db'),
	'PORT': os.getenv('DB_PORT', '5432'),
	'NAME': os.getenv('DB_NAME', 'django_rest_template'),
	'USER': os.getenv('DB_USERNAME', 'django_rest_template'),
	'PASSWORD': os.getenv('DB_PASSWORD', 'django_rest_template'),
	'OPTIONS': {
		'sql_mode': 'STRICT_TRANS_TABLES',
	}
}

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.postgresql',
		**DEFAULT_OPTS,
		'OPTIONS': {}
	},
}

# Languages available for translation; used by locale middleware.
LANGUAGES = (
	('en-gb', 'British English'),
	('en-us', 'American English'),
	('en-ca', 'Canadian English'),
	('fr', 'French'),
	('es', 'Spanish'),
)

AUTHENTICATION_BACKENDS = [
	'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'django_rest_template.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [
			os.path.join(BASE_DIR, 'templates')
		],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.contrib.auth.context_processors.auth',
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.template.context_processors.i18n',
				'django.template.context_processors.media',
				'django.template.context_processors.static',
				'django.template.context_processors.tz',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
				'django_rest_template.apps.common.tpl_context.site_vars',
			],
		},
	},
]

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

REST_FRAMEWORK = {
	'DEFAULT_PAGINATION_CLASS': None,
	'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
	'DEFAULT_RENDERER_CLASSES': (
		'django_rest_template.apps.common.psp_camel_case.render.CamelCaseJSONRenderer',),
	'DEFAULT_PARSER_CLASSES': (
		'django_rest_template.apps.common.psp_camel_case.parser.CamelCaseJSONParser',),
	'DEFAULT_PERMISSION_CLASSES': (
		'rest_framework.permissions.IsAuthenticated',
	),
	'DEFAULT_AUTHENTICATION_CLASSES': (
		'django_rest_template.apps.user.authentication.JSONWebTokenAuthenticationPost',
	),
	'EXCEPTION_HANDLER': 'django_rest_template.apps.common.exception_handler'
}

JWT_AUTH = {
	'JWT_VERIFY_EXPIRATION': False,
	'JWT_RESPONSE_PAYLOAD_HANDLER':
		'django_rest_template.apps.user.utils.psp_jwt_response_payload_handler',
	'JWT_PAYLOAD_HANDLER': 'django_rest_template.apps.user.utils.psp_jwt_payload_handler'
}

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_HEADERS = (
	'x-requested-with',
	'content-type',
	'accept',
	'origin',
	'authorization',
	'x-csrftoken',
	'user-agent',
	'accept-encoding',
	'if-modified-since',
)

WSGI_APPLICATION = 'django_rest_template.wsgi.application'

SECRET_KEY = '(3r#690b&r#!2po+m5n_x(wys7-(z8b+&yq(q2y*l4w$yk5-^%'

DEBUG = os.getenv('DEBUG', False)

PSP_DASHBOARD_URL = 'https://stg-%s.djangoresttemplate.com/dashboard-'

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# Additional locations of static files
STATICFILES_DIRS = [
	os.path.join(BASE_DIR, 'public'),
]

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

FIXTURE_DIRS = [
	os.path.join(BASE_DIR, 'fixtures'),
	os.path.join(BASE_DIR, 'fixtures/test'),
]

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_PORT = 587

SERVER_EMAIL = 'no-reply@djangoresttemplate.com'
DEFAULT_FROM_EMAIL = 'no-reply@djangoresttemplate.com'

FILE_UPLOAD_HANDLERS = ('django.core.files.uploadhandler.TemporaryFileUploadHandler',)

FILE_UPLOAD_MAX_ATTACH_NUM = 10

# in bytes, see https://docs.djangoproject.com/en/1.8/ref/files/file/#django.core.files.File.size
FILE_UPLOAD_MAX_SIZE = 10 * 1024 * 1024

FILE_UPLOAD_TYPES = [
	'application/pdf', 'image/png', 'image/jpeg', 'application/msword',
	'application/vnd.ms-excel', 'application/vnd.ms-office']

LOGGING = {
	'version': 1,
	'disable_existing_loggers': False,
	'formatters': {
		'simple': {
			'format': '[%(asctime)s] %(levelname)s %(message)s',
			'datefmt': '%Y-%m-%d %H:%M:%S'
		},
		'verbose': {
			'format': '[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s',
			'datefmt': '%Y-%m-%d %H:%M:%S'
		},
	},
	'handlers': {
		'console': {
			'level': 'DEBUG',
			'class': 'logging.StreamHandler',
			'formatter': 'simple',
		},
		# 'file': {
		# 	'level': 'DEBUG',
		# 	'class': 'logging.handlers.TimedRotatingFileHandler',
		# 	'when': 'midnight',
		# 	'filename': '/var/log/django_rest_template/django_rest_template.log',
		# 	'formatter': 'verbose',
		# },
		'logstash': {
			'level': 'DEBUG',
			'class': 'logstash.TCPLogstashHandler',
			'host': os.getenv('LOGSTASH_HOST', 'localhost'),
			'port': os.getenv('LOGSTASH_PORT', '5959'),  # Default value: 5959
			'version': 1,
			'message_type': 'django',
			# 'type' field in logstash message. Default value: 'logstash'.
			'fqdn': False,  # Fully qualified domain name. Default value: false.
			'tags': ['django.request'],  # list of tags. Default: None.
		},
		'elasticapm': {
			'level': 'WARNING',
			'class': 'elasticapm.contrib.django.handlers.LoggingHandler',
		},
		# 'request_handler': {
		# 	'level': 'DEBUG',
		# 	'class': 'logging.handlers.RotatingFileHandler',
		# 	'filename': '/var/log/django_rest_template/requests.log',
		# 	'maxBytes': 1024 * 1024 * 5,  # 5MB
		# 	'backupCount': 5,
		# 	'formatter': 'simple'
		# }
	},
	'loggers': {
		'django_rest_template': {
			'handlers': ['elasticapm', 'console'],
			# 'handlers': ['elasticapm', 'console', 'file'],
			'level': 'DEBUG',
			'propagate': True,
		},
		'django.request': {
			'handlers': ['logstash', 'console'],
			# 'handlers': ['logstash', 'request_handler'],
			'level': 'DEBUG',
			'propagate': False
		},
		'elasticapm.errors': {
			'level': 'ERROR',
			'handlers': ['console'],
			'propagate': False,
		},
	}
}

PASSWORD_RESET_TIMEOUT_DAYS = 1

SSL_ENABLED = True

SWAGGER_SETTINGS = {
	'api_version': '1.0',
	'info': {
		'description':
			'This is the official API documentation for the Django Rest template management software',
		'title': 'Django Rest Template API Documentation'
	},
	'api_path': '/api/',
	'base_path': 'local.djangoresttemplate.com/api/docs'
}

GRAPPELLI_ADMIN_TITLE = 'Django Rest Template'

ELASTICSEARCH_DSL = {
	'default': {
		'hosts': os.getenv('ES_HOST', 'localhost:9200'),
		'http_auth': (os.getenv('ES_USER', 'elastic'), os.getenv('ES_PASSWORD', 'elastic'))
	},
}

ELASTIC_APM = {
	# Set required service name. Allowed characters:
	# a-z, A-Z, 0-9, -, _, and space
	'SERVICE_NAME': 'rest-api',
	# Use if APM Server requires a token
	'SECRET_TOKEN': '',
	# Set custom APM Server URL (default: http://localhost:8200)
	'SERVER_URL': os.getenv('ES_APM_URL', 'http://localhost:8200'),
	'DEBUG': DEBUG,
}

# CELERY STUFF
RMQ = {
	'db': {
		'ROUTING_KEY': 'rest_api.db.%ss.%ss',
	},
	'schedule': {
		'ROUTING_KEY': 'rest_api.schedule.remind',
	},
	'QUEUE_NAME': 'psp.q.rest_api',
	'MASTER_EXCHANGE': 'psp.ex',
	'TEST_PREFIX': 'test_',
	'HOST': os.getenv('RABBITMQ_HOST', 'localhost'),
	'admin_user': os.getenv('RABBITMQ_DEFAULT_USER', ''),
	'admin_pass': os.getenv('RABBITMQ_DEFAULT_PASS', ''),
}

BROKER_URL = 'amqp://%s:%s@%s/' % (
	os.getenv('RABBITMQ_DEFAULT_USER', ''),
	os.getenv('RABBITMQ_DEFAULT_PASS', ''),
	os.getenv('RABBITMQ_HOST', 'localhost')
)
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
